import { addIcons } from 'ionicons';
import {
  add,
  alertCircleOutline,
  chevronForward,
  createOutline,
  documentTextOutline,
  handLeftOutline,
  helpCircleOutline,
  homeOutline,
  languageOutline,
  libraryOutline,
  lockClosedOutline,
  logOutOutline,
  mailOutline,
  notificationsOutline,
  peopleOutline,
  personAddOutline,
  personCircleOutline,
  searchOutline,
  shareSocialOutline,
  shieldCheckmarkOutline,
} from 'ionicons/icons';

addIcons({
  add,
  'alert-circle-outline': alertCircleOutline,
  'chevron-forward': chevronForward,
  'create-outline': createOutline,
  'document-text-outline': documentTextOutline,
  'hand-left-outline': handLeftOutline,
  'help-circle-outline': helpCircleOutline,
  'home-outline': homeOutline,
  'language-outline': languageOutline,
  'library-outline': libraryOutline,
  'lock-closed-outline': lockClosedOutline,
  'log-out-outline': logOutOutline,
  'mail-outline': mailOutline,
  'notifications-outline': notificationsOutline,
  'people-outline': peopleOutline,
  'person-add-outline': personAddOutline,
  'person-circle-outline': personCircleOutline,
  'search-outline': searchOutline,
  'share-social-outline': shareSocialOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
});
